#include <Arduino.h>

#define PAYLOAD_TYPE_SYNC 1
#define PAYLOAD_TYPE_EXECUTE 2
#define PAYLOAD_TYPE_STATE 3

#define PAYLOAD_SUB_TYPE_NONE 0
#define PAYLOAD_SUB_TYPE_NOTIFY 1
#define PAYLOAD_SUB_TYPE_REPORT 2
#define PAYLOAD_SUB_TYPE_ALERT 3
